version: 1.1.0.{build}
configuration: Release
platform: x64
build:
  project: 15_puzzle_dx.sln
  verbosity: normal
after_build:
- cmd: >-
    7z a 15_puzzle_dx.7z .\x64\Release\15_puzzle_dx.exe

    7z a 15_puzzle_dx.7z .\x64\Release\ps.cso

    7z a 15_puzzle_dx.7z .\x64\Release\vs.cso

    7z a 15_puzzle_dx.7z data\texture.tga
artifacts:
- path: 15_puzzle_dx.7z
  name: 15 Puzzle