version: 1.1.2.{build}
skip_tags: true
configuration: Release
platform:
- x64
- x86
build:
  project: 15_puzzle_dx.sln
  verbosity: normal
after_build:
- cmd: 7z a 15_puzzle_dx_%PLATFORM%.7z .\%PLATFORM%\%CONFIGURATION%\bin\*
artifacts:
- path: 15_puzzle_dx_%PLATFORM%.7z