version: 1.1.1.{build}
skip_tags: true
configuration: Release
platform: x64
build:
  project: 15_puzzle_dx.sln
  verbosity: normal
after_build:
- cmd: 7z a 15_puzzle_dx.7z .\x64\Release\bin\*
artifacts:
- path: 15_puzzle_dx.7z
  name: 15 Puzzle