version: 1.1.2.{build}
skip_tags: true
configuration: Release
platform:
- x64
- x86
build:
  project: 15_puzzle_dx.sln
  verbosity: normal
after_build:
- cmd: 7z a 15_puzzle_dx_$(PlatformShortName).7z $(SolutionDir)$(PlatformShortName)\$(Configuration)\bin\*
artifacts:
- path: 15_puzzle_dx_$(PlatformShortName).7z